### ISSUE TITLE
Create a "leave" button in the game, which allows to return to the user profile.

### ISSUE THREAD

**Issue by marvinmuenger** [sopra-fs21-group-08/sopra-fs21-group08-client#48]
Time estimate: 0.5h

This task is part of user story #21

**Comment by zoyakatashinskaya** [comment]
maybe we can integrate this functionality in the player component? for example if you click on player card you get a massage asking if you want to leave game. The idea is that we save space on the screen for a button that is actually should not be used often.

**Comment by marvinmuenger** [comment]
ae71e13
