### ISSUE TITLE
Create a register page for creating a new user and send the input data to the backend.

### ISSUE THREAD

**Issue by marvinmuenger** [sopra-fs21-group-08/sopra-fs21-group08-client#56]
Time estimate: 2h

This task is part of user story #52

**Comment by tobifra** [comment]
311c864a02a6bf44f34d787c916be3ca7b149d11

**Comment by tobifra** [comment]
16c935c82476e1302f75c4330b79cf17433b7094

**Comment by tobifra** [comment]
3a50ba2b4fc473cd7bb5089d2724eb5569a15243
