### ISSUE TITLE
Create a login page and send the input data to the backend.

### ISSUE THREAD

**Issue by marvinmuenger** [sopra-fs21-group-08/sopra-fs21-group08-client#57]
Time estimate: 2h

This task is part of user story #53

**Comment by tobifra** [comment]
16c935c82476e1302f75c4330b79cf17433b7094

**Comment by tobifra** [comment]
dc9ac4adf09f94dcecce8649f0c43e8c2e5b6891

**Comment by tobifra** [comment]
8f6196cf15e31e6973b3d3343a31d046b2b98aac

**Comment by tobifra** [comment]
3a50ba2b4fc473cd7bb5089d2724eb5569a15243
