### ISSUE TITLE
Create a Lobby Screen where all the joined players are displayed.

### ISSUE THREAD

**Issue by marvinmuenger** [sopra-fs21-group-08/sopra-fs21-group08-client#58]
Time estimate: 6h

This task is part of user story #2 #3 

- [x] fetch users from the backend
- [x] redirect to game page (/game/{id})
- [x] leave game by deleting player from a list of players
- [x] change app routing to game/lobby/{id}

**Comment by zoyakatashinskaya** [comment]
- [x] change routing in Profile/joinLobby

**Comment by zoyakatashinskaya** [comment]
- [ ] redirect all players from lobby to the game
