### ISSUE TITLE
Implement the game over functionality

### ISSUE THREAD

**Issue by zoyakatashinskaya** [sopra-fs21-group-08/sopra-fs21-group08-client#80]
- [x] information about winner(s) is displayed
- [x] Redirect to User Profile
- [x] Add sound effects

Optional:
- [x] confetti effect for the winner

Time estimate: 3 h

This task is part of user story: #22, #21 

- [x] Connect with backend

**Comment by marvinmuenger** [comment]
55319c2

**Comment by marvinmuenger** [comment]
5281dd2

**Comment by marvinmuenger** [comment]
666ec95
